let playersDB = [
  { id: 1, name: "Kubala", position: "ATK", rating: 97, rarity: "relic", img: "images/cards/retired/retired/kubala.png", teams: ["FC Barcelona"], country: "Hungary" },
  { id: 2, name: "Sergio Mestre", position: "GK", rating: 63, rarity: "common", img: "images/cards/la-liga/real-madrid/sergiomestre.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 3, name: "Javi Navarro", position: "GK", rating: 68, rarity: "common", img: "images/cards/la-liga/real-madrid/javinavarro.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 4, name: "Thiago Pitarch", position: "MID", rating: 68, rarity: "common", img: "images/cards/la-liga/real-madrid/thiagopitarch.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 5, name: "Diego Aguado", position: "DEF", rating: 69, rarity: "common", img: "images/cards/la-liga/real-madrid/diegoaguado.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 6, name: "Fran Gonzalez", position: "GK", rating: 72, rarity: "common", img: "images/cards/la-liga/real-madrid/frangonzalez.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 7, name: "Gonzalo Garcia", position: "ATK", rating: 76, rarity: "common", img: "images/cards/la-liga/real-madrid/gonzalogarcia.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 8, name: "Raul Asencio", position: "DEF", rating: 80, rarity: "common", img: "images/cards/la-liga/real-madrid/raulasencio.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 9, name: "Fran Garcia", position: "DEF", rating: 81, rarity: "common", img: "images/cards/la-liga/real-madrid/frangarcia.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 10, name: "Mastantuono", position: "ATK", rating: 82, rarity: "common", img: "images/cards/la-liga/real-madrid/mastantuono.png", teams: ["Real Madrid"], country: "Argentina" },
  { id: 11, name: "Dani Ceballos", position: "MID", rating: 82, rarity: "common", img: "images/cards/la-liga/real-madrid/daniceballos.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 12, name: "Ferland Mendy", position: "DEF", rating: 82, rarity: "common", img: "images/cards/la-liga/real-madrid/ferlandmendy.png", teams: ["Real Madrid"], country: "France" },
  { id: 13, name: "Lamine Yamal", position: "ATK", rating: 95, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/lamineyamal.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 14, name: "Raphinha", position: "ATK", rating: 94, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/raphinha.png", teams: ["FC Barcelona"], country: "Brasil" },
  { id: 15, name: "Alvaro Carreras", position: "DEF", rating: 82, rarity: "common", img: "images/cards/la-liga/real-madrid/alvarocarreras.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 16, name: "Endrick", position: "ATK", rating: 83, rarity: "rare", img: "images/cards/la-liga/real-madrid/endrick.png", teams: ["Real Madrid"], country: "Brasil" },
  { id: 17, name: "Pedri", position: "MID", rating: 93, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/pedri.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 18, name: "Brahim Diaz", position: "MID", rating: 83, rarity: "rare", img: "images/cards/la-liga/real-madrid/brahimdiaz.png", teams: ["Real Madrid"], country: "Morocco" },
  { id: 19, name: "David Alaba", position: "DEF", rating: 84, rarity: "rare", img: "images/cards/la-liga/real-madrid/davidalaba.png", teams: ["Real Madrid"], country: "Austria" },
  { id: 20, name: "Andriy Lunin", position: "GK", rating: 83, rarity: "rare", img: "images/cards/la-liga/real-madrid/andriylunin.png", teams: ["Real Madrid"], country: "Ukraine" },
  { id: 21, name: "Dean Huijsen", position: "DEF", rating: 84, rarity: "rare", img: "images/cards/la-liga/real-madrid/deanhuijsen.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 22, name: "Robert Lewandoski", position: "ATK", rating: 92, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/robertlewandoski.png", teams: ["FC Barcelona"], country: "Poland" },
  { id: 23, name: "Eduardo Camavinga", position: "MID", rating: 85, rarity: "rare", img: "images/cards/la-liga/real-madrid/eduardocamavinga.png", teams: ["Real Madrid"], country: "France" },
  { id: 24, name: "Frenkie De Jong", position: "MID", rating: 91, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/frenkiedejong.png", teams: ["FC Barcelona"], country: "Netherlands" },
  { id: 25, name: "Joan Garcia", position: "GK", rating: 89, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/joangarcia.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 26, name: "Ter Stegen", position: "GK", rating: 88, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/terstegen.png", teams: ["FC Barcelona"], country: "Germany" },
  { id: 27, name: "Gavi", position: "MID", rating: 87, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/gavi.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 28, name: "Dani Carvajal", position: "DEF", rating: 85, rarity: "rare", img: "images/cards/la-liga/real-madrid/danicarvajal.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 29, name: "Fermin", position: "MID", rating: 88, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/fermin.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 30, name: "Pau Cubarsi", position: "DEF", rating: 87, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/paucubarsi.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 31, name: "Jules Kounde", position: "DEF", rating: 87, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/juleskounde.png", teams: ["FC Barcelona"], country: "France" },
  { id: 32, name: "Dani Olmo", position: "MID", rating: 86, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/daniolmo.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 33, name: "Marcus Rashford", position: "ATK", rating: 87, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/marcusrashford.png", teams: ["FC Barcelona"], country: "England" },
  { id: 34, name: "Eric Garcia", position: "DEF", rating: 85, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/ericgarcia.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 35, name: "Ferran Torres", position: "ATK", rating: 85, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/ferrantorres.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 36, name: "Andreas Christensen", position: "DEF", rating: 83, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/andreaschristensen.png", teams: ["FC Barcelona"], country: "Denmark" },
  { id: 37, name: "Marc Bernal", position: "MID", rating: 83, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/marcbernal.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 38, name: "Ronald Araujo", position: "DEF", rating: 82, rarity: "common", img: "images/cards/la-liga/fc-barcelona/ronaldaraujo.png", teams: ["FC Barcelona"], country: "Uruguay" },
  { id: 39, name: "Wojciech Szczęsny", position: "GK", rating: 82, rarity: "common", img: "images/cards/la-liga/fc-barcelona/wojciechszczesny.png", teams: ["FC Barcelona"], country: "Poland" },
  { id: 40, name: "Gerard Martin", position: "DEF", rating: 81, rarity: "common", img: "images/cards/la-liga/fc-barcelona/gerardmartin.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 41, name: "Marc Casado", position: "MID", rating: 81, rarity: "common", img: "images/cards/la-liga/fc-barcelona/marccasado.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 42, name: "Roony Bardghji", position: "ATK", rating: 81, rarity: "common", img: "images/cards/la-liga/fc-barcelona/roonybardghji.png", teams: ["FC Barcelona"], country: "Sweden" },
  { id: 43, name: "Dro", position: "MID", rating: 79, rarity: "common", img: "images/cards/la-liga/fc-barcelona/dro.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 44, name: "Toni Fernandez", position: "MID", rating: 78, rarity: "common", img: "images/cards/la-liga/fc-barcelona/tonifernandez.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 45, name: "Jofre Torrents", position: "DEF", rating: 77, rarity: "common", img: "images/cards/la-liga/fc-barcelona/jofretorrents.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 46, name: "Guille fernandez", position: "MID", rating: 76, rarity: "common", img: "images/cards/la-liga/fc-barcelona/guillefernandez.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 47, name: "Diego Kochen", position: "GK", rating: 74, rarity: "common", img: "images/cards/la-liga/fc-barcelona/diegokochen.png", teams: ["FC Barcelona"], country: "EEUU" },
  { id: 48, name: "Eder Aller", position: "GK", rating: 68, rarity: "common", img: "images/cards/la-liga/fc-barcelona/ederaller.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 49, name: "Alejandro Balde", position: "DEF", rating: 86, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/alejandrobalde.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 50, name: "Arda Guler", position: "MID", rating: 86, rarity: "rare", img: "images/cards/la-liga/real-madrid/ardaguler.png", teams: ["Real Madrid"], country: "Turkey" },
  { id: 51, name: "Antonio Rudiger", position: "DEF", rating: 86, rarity: "rare", img: "images/cards/la-liga/real-madrid/antoniorudiger.png", teams: ["FC Barcelona"], country: "Germany" },
  { id: 52, name: "Rodrygo Goes", position: "ATK", rating: 87, rarity: "epic", img: "images/cards/la-liga/real-madrid/rodrygogoes.png", teams: ["Real Madrid"], country: "Brasil" },
  { id: 53, name: "Aurelien Tchouameni", position: "MID", rating: 87, rarity: "epic", img: "images/cards/la-liga/real-madrid/aurelientchouameni.png", teams: ["Real Madrid"], country: "France" },
  { id: 54, name: "Trent Alexander-Arnold", position: "DEF", rating: 88, rarity: "epic", img: "images/cards/la-liga/real-madrid/trentalexanderarnold.png", teams: ["Real Madrid"], country: "England" },
  { id: 55, name: "Eder Militao", position: "DEF", rating: 88, rarity: "epic", img: "images/cards/la-liga/real-madrid/edermilitao.png", teams: ["Real Madrid"], country: "Brasil" },
  { id: 56, name: "Fede Valverde", position: "MID", rating: 89, rarity: "epic", img: "images/cards/la-liga/real-madrid/fedevalverde.png", teams: ["Real Madrid"], country: "Uruguay" },
  { id: 57, name: "Jude Bellingham", position: "MID", rating: 91, rarity: "legendary", img: "images/cards/la-liga/real-madrid/judebellingham.png", teams: ["Real Madrid"], country: "England" },
  { id: 58, name: "Vinicius Jr", position: "ATK", rating: 92, rarity: "legendary", img: "images/cards/la-liga/real-madrid/viniciusjr.png", teams: ["Real Madrid"], country: "Brasil" },
  { id: 59, name: "Kylian Mbappe", position: "ATK", rating: 95, rarity: "legendary", img: "images/cards/la-liga/real-madrid/kylianmbappe.png", teams: ["Real Madrid"], country: "France" },
  { id: 60, name: "Thibaut Courtois", position: "GK", rating: 95, rarity: "legendary", img: "images/cards/la-liga/real-madrid/thibautcourtois.png", teams: ["Real Madrid"], country: "Belgium" },
  { id: 61, name: "Alfredo Di Stefano", position: "ATK", rating: 98, rarity: "relic", img: "images/cards/retired/retired/alfredodistefano.png", teams: ["retired"], country: "Argentina" },
];
