let playersDB = [
  { id: 1, name: "Kubala", position: "ATK", rating: 97, rarity: "relic", img: "images/cards/retired/retired/kubala.png", teams: ["FC Barcelona"], country: "Hungary" },
  { id: 2, name: "Sergio Mestre", position: "GK", rating: 63, rarity: "common", img: "images/cards/la-liga/real-madrid/sergiomestre.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 3, name: "Javi Navarro", position: "GK", rating: 68, rarity: "common", img: "images/cards/la-liga/real-madrid/javinavarro.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 4, name: "Thiago Pitarch", position: "MID", rating: 68, rarity: "common", img: "images/cards/la-liga/real-madrid/thiagopitarch.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 5, name: "Diego Aguado", position: "DEF", rating: 69, rarity: "common", img: "images/cards/la-liga/real-madrid/diegoaguado.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 6, name: "Fran Gonzalez", position: "GK", rating: 72, rarity: "common", img: "images/cards/la-liga/real-madrid/frangonzalez.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 7, name: "Gonzalo Garcia", position: "ATK", rating: 76, rarity: "common", img: "images/cards/la-liga/real-madrid/gonzalogarcia.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 8, name: "Raul Asencio", position: "DEF", rating: 80, rarity: "common", img: "images/cards/la-liga/real-madrid/raulasencio.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 9, name: "Fran Garcia", position: "DEF", rating: 81, rarity: "common", img: "images/cards/la-liga/real-madrid/frangarcia.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 10, name: "Mastantuono", position: "ATK", rating: 82, rarity: "common", img: "images/cards/la-liga/real-madrid/mastantuono.png", teams: ["Real Madrid"], country: "Argentina" },
  { id: 11, name: "Dani Ceballos", position: "MID", rating: 82, rarity: "common", img: "images/cards/la-liga/real-madrid/daniceballos.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 12, name: "Ferland Mendy", position: "DEF", rating: 82, rarity: "common", img: "images/cards/la-liga/real-madrid/ferlandmendy.png", teams: ["Real Madrid"], country: "France" },
  { id: 13, name: "Lamine Yamal", position: "ATK", rating: 95, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/lamineyamal.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 14, name: "Raphinha", position: "ATK", rating: 94, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/raphinha.png", teams: ["FC Barcelona"], country: "Brasil" },
  { id: 15, name: "Alvaro Carreras", position: "DEF", rating: 82, rarity: "common", img: "images/cards/la-liga/real-madrid/alvarocarreras.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 16, name: "Endrick", position: "ATK", rating: 83, rarity: "rare", img: "images/cards/la-liga/real-madrid/endrick.png", teams: ["Real Madrid"], country: "Brasil" },
  { id: 17, name: "Pedri", position: "MID", rating: 93, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/pedri.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 18, name: "Brahim Diaz", position: "MID", rating: 83, rarity: "rare", img: "images/cards/la-liga/real-madrid/brahimdiaz.png", teams: ["Real Madrid"], country: "Morocco" },
  { id: 19, name: "David Alaba", position: "DEF", rating: 84, rarity: "rare", img: "images/cards/la-liga/real-madrid/davidalaba.png", teams: ["Real Madrid"], country: "Austria" },
  { id: 20, name: "Andriy Lunin", position: "GK", rating: 83, rarity: "rare", img: "images/cards/la-liga/real-madrid/andriylunin.png", teams: ["Real Madrid"], country: "Ukraine" },
  { id: 21, name: "Dean Huijsen", position: "DEF", rating: 84, rarity: "rare", img: "images/cards/la-liga/real-madrid/deanhuijsen.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 22, name: "Robert Lewandoski", position: "ATK", rating: 92, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/robertlewandoski.png", teams: ["FC Barcelona"], country: "Poland" },
  { id: 23, name: "Eduardo Camavinga", position: "MID", rating: 85, rarity: "rare", img: "images/cards/la-liga/real-madrid/eduardocamavinga.png", teams: ["Real Madrid"], country: "France" },
  { id: 24, name: "Frenkie De Jong", position: "MID", rating: 91, rarity: "legendary", img: "images/cards/la-liga/fc-barcelona/frenkiedejong.png", teams: ["FC Barcelona"], country: "Netherlands" },
  { id: 25, name: "Joan Garcia", position: "GK", rating: 89, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/joangarcia.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 26, name: "Ter Stegen", position: "GK", rating: 88, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/terstegen.png", teams: ["FC Barcelona"], country: "Germany" },
  { id: 27, name: "Gavi", position: "MID", rating: 87, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/gavi.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 28, name: "Dani Carvajal", position: "DEF", rating: 85, rarity: "rare", img: "images/cards/la-liga/real-madrid/danicarvajal.png", teams: ["Real Madrid"], country: "Spain" },
  { id: 29, name: "Fermin", position: "MID", rating: 88, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/fermin.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 30, name: "Pau Cubarsi", position: "DEF", rating: 87, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/paucubarsi.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 31, name: "Jules Kounde", position: "DEF", rating: 87, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/juleskounde.png", teams: ["FC Barcelona"], country: "France" },
  { id: 32, name: "Dani Olmo", position: "MID", rating: 86, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/daniolmo.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 33, name: "Marcus Rashford", position: "ATK", rating: 87, rarity: "epic", img: "images/cards/la-liga/fc-barcelona/marcusrashford.png", teams: ["FC Barcelona"], country: "England" },
  { id: 34, name: "Eric Garcia", position: "DEF", rating: 85, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/ericgarcia.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 35, name: "Ferran Torres", position: "ATK", rating: 85, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/ferrantorres.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 36, name: "Andreas Christensen", position: "DEF", rating: 83, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/andreaschristensen.png", teams: ["FC Barcelona"], country: "Denmark" },
  { id: 37, name: "Marc Bernal", position: "MID", rating: 83, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/marcbernal.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 38, name: "Ronald Araujo", position: "DEF", rating: 82, rarity: "common", img: "images/cards/la-liga/fc-barcelona/ronaldaraujo.png", teams: ["FC Barcelona"], country: "Uruguay" },
  { id: 39, name: "Wojciech Szczęsny", position: "GK", rating: 82, rarity: "common", img: "images/cards/la-liga/fc-barcelona/wojciechszczesny.png", teams: ["FC Barcelona"], country: "Poland" },
  { id: 40, name: "Gerard Martin", position: "DEF", rating: 81, rarity: "common", img: "images/cards/la-liga/fc-barcelona/gerardmartin.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 41, name: "Marc Casado", position: "MID", rating: 81, rarity: "common", img: "images/cards/la-liga/fc-barcelona/marccasado.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 42, name: "Roony Bardghji", position: "ATK", rating: 81, rarity: "common", img: "images/cards/la-liga/fc-barcelona/roonybardghji.png", teams: ["FC Barcelona"], country: "Sweden" },
  { id: 43, name: "Dro", position: "MID", rating: 79, rarity: "common", img: "images/cards/la-liga/fc-barcelona/dro.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 44, name: "Toni Fernandez", position: "MID", rating: 78, rarity: "common", img: "images/cards/la-liga/fc-barcelona/tonifernandez.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 45, name: "Jofre Torrents", position: "DEF", rating: 77, rarity: "common", img: "images/cards/la-liga/fc-barcelona/jofretorrents.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 46, name: "Guille fernandez", position: "MID", rating: 76, rarity: "common", img: "images/cards/la-liga/fc-barcelona/guillefernandez.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 47, name: "Diego Kochen", position: "GK", rating: 74, rarity: "common", img: "images/cards/la-liga/fc-barcelona/diegokochen.png", teams: ["FC Barcelona"], country: "EEUU" },
  { id: 48, name: "Eder Aller", position: "GK", rating: 68, rarity: "common", img: "images/cards/la-liga/fc-barcelona/ederaller.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 49, name: "Alejandro Balde", position: "DEF", rating: 86, rarity: "rare", img: "images/cards/la-liga/fc-barcelona/alejandrobalde.png", teams: ["FC Barcelona"], country: "Spain" },
  { id: 50, name: "Arda Guler", position: "MID", rating: 86, rarity: "rare", img: "images/cards/la-liga/real-madrid/ardaguler.png", teams: ["Real Madrid"], country: "Turkey" },
  { id: 51, name: "Antonio Rudiger", position: "DEF", rating: 86, rarity: "rare", img: "images/cards/la-liga/real-madrid/antoniorudiger.png", teams: ["Real Madrid"], country: "Germany" },
  { id: 52, name: "Rodrygo Goes", position: "ATK", rating: 87, rarity: "epic", img: "images/cards/la-liga/real-madrid/rodrygogoes.png", teams: ["Real Madrid"], country: "Brasil" },
  { id: 53, name: "Aurelien Tchouameni", position: "MID", rating: 87, rarity: "epic", img: "images/cards/la-liga/real-madrid/aurelientchouameni.png", teams: ["Real Madrid"], country: "France" },
  { id: 54, name: "Trent Alexander-Arnold", position: "DEF", rating: 88, rarity: "epic", img: "images/cards/la-liga/real-madrid/trentalexanderarnold.png", teams: ["Real Madrid"], country: "England" },
  { id: 55, name: "Eder Militao", position: "DEF", rating: 88, rarity: "epic", img: "images/cards/la-liga/real-madrid/edermilitao.png", teams: ["Real Madrid"], country: "Brasil" },
  { id: 56, name: "Fede Valverde", position: "MID", rating: 89, rarity: "epic", img: "images/cards/la-liga/real-madrid/fedevalverde.png", teams: ["Real Madrid"], country: "Uruguay" },
  { id: 57, name: "Jude Bellingham", position: "MID", rating: 91, rarity: "legendary", img: "images/cards/la-liga/real-madrid/judebellingham.png", teams: ["Real Madrid"], country: "England" },
  { id: 58, name: "Vinicius Jr", position: "ATK", rating: 92, rarity: "legendary", img: "images/cards/la-liga/real-madrid/viniciusjr.png", teams: ["Real Madrid"], country: "Brasil" },
  { id: 59, name: "Kylian Mbappe", position: "ATK", rating: 95, rarity: "legendary", img: "images/cards/la-liga/real-madrid/kylianmbappe.png", teams: ["Real Madrid"], country: "France" },
  { id: 60, name: "Thibaut Courtois", position: "GK", rating: 95, rarity: "legendary", img: "images/cards/la-liga/real-madrid/thibautcourtois.png", teams: ["Real Madrid"], country: "Belgium" },
  { id: 61, name: "Alfredo Di Stefano", position: "ATK", rating: 98, rarity: "relic", img: "images/cards/retired/retired/alfredodistefano.png", teams: ["retired"], country: "Argentina" },
  { id: 62, name: "Julian Alvarez", position: "ATK", rating: 93, rarity: "legendary", img: "images/cards/la-liga/atletico-de-madrid/julianalvarez.png", teams: ["Atletico de Madrid"], country: "Argentina" },
  { id: 63, name: "Jan Oblak", position: "GK", rating: 91, rarity: "legendary", img: "images/cards/la-liga/atletico-de-madrid/janoblak.png", teams: ["Atletico de Madrid"], country: "Slovenia" },
  { id: 64, name: "Antoine Griezmann", position: "ATK", rating: 89, rarity: "epic", img: "images/cards/la-liga/atletico-de-madrid/antoinegriezmann.png", teams: ["Atletico de Madrid"], country: "France" },
  { id: 65, name: "Alex Baena", position: "MID", rating: 86, rarity: "rare", img: "images/cards/la-liga/atletico-de-madrid/alexbaena.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 66, name: "Giuliano Simeone", position: "ATK", rating: 85, rarity: "rare", img: "images/cards/la-liga/atletico-de-madrid/giulianosimeone.png", teams: ["Atletico de Madrid"], country: "Argentina" },
  { id: 67, name: "Le Normand", position: "DEF", rating: 84, rarity: "rare", img: "images/cards/la-liga/atletico-de-madrid/lenormand.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 68, name: "Alexander Sorloth", position: "ATK", rating: 84, rarity: "rare", img: "images/cards/la-liga/atletico-de-madrid/alexandersorloth.png", teams: ["Atletico de Madrid"], country: "Norway" },
  { id: 69, name: "Jose Maria Gimenez", position: "DEF", rating: 83, rarity: "rare", img: "images/cards/la-liga/atletico-de-madrid/josemariagimenez.png", teams: ["Atletico de Madrid"], country: "Uruguay" },
  { id: 70, name: "Koke Resurreccion", position: "MID", rating: 83, rarity: "rare", img: "images/cards/la-liga/atletico-de-madrid/kokeresurreccion.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 71, name: "Marcos Llorente", position: "MID", rating: 83, rarity: "rare", img: "images/cards/la-liga/atletico-de-madrid/marcosllorente.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 72, name: "Connor Gallagher", position: "MID", rating: 82, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/connorgallagher.png", teams: ["Atletico de Madrid"], country: "England" },
  { id: 73, name: "Thiago Almada", position: "MID", rating: 82, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/thiagoalmada.png", teams: ["Atletico de Madrid"], country: "Argentina" },
  { id: 74, name: "Nahuel Molina", position: "DEF", rating: 81, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/nahuelmolina.png", teams: ["Atletico de Madrid"], country: "Argentina" },
  { id: 75, name: "Johnny Cardoso", position: "MID", rating: 81, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/johnnycardoso.png", teams: ["Atletico de Madrid"], country: "EEUU" },
  { id: 76, name: "David Hancko", position: "DEF", rating: 80, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/davidhancko.png", teams: ["Atletico de Madrid"], country: "Slovakia" },
  { id: 77, name: "Pablo Barrios", position: "MID", rating: 79, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/pablobarrios.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 78, name: "Javi Galan", position: "MID", rating: 79, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/javigalan.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 79, name: "Matteo Ruggeri", position: "MID", rating: 78, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/matteoruggeri.png", teams: ["Atletico de Madrid"], country: "Italy" },
  { id: 80, name: "Giacomo Raspadori", position: "ATK", rating: 78, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/giacomoraspadori.png", teams: ["Atletico de Madrid"], country: "Italy" },
  { id: 81, name: "Juan Muso", position: "GK", rating: 77, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/juanmuso.png", teams: ["Atletico de Madrid"], country: "Argentina" },
  { id: 82, name: "Nico Gonzalez", position: "ATK", rating: 77, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/nicogonzalez.png", teams: ["Atletico de Madrid"], country: "Argentina" },
  { id: 83, name: "Clement Lenglet", position: "DEF", rating: 75, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/clementlenglet.png", teams: ["Atletico de Madrid"], country: "France" },
  { id: 84, name: "Marc Pubill", position: "DEF", rating: 74, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/marcpubill.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 85, name: "Carlos Martin", position: "MID", rating: 72, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/carlosmartin.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 86, name: "Salvi Esquivel", position: "GK", rating: 68, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/salviesquivel.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 87, name: "Ilias Kostis", position: "DEF", rating: 67, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/iliaskostis.png", teams: ["Atletico de Madrid"], country: "Greece" },
  { id: 88, name: "Jano Monserrate", position: "MID", rating: 66, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/janomonserrate.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 89, name: "Rayane Belaid", position: "ATK", rating: 66, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/rayanebelaid.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 90, name: "Taufik Seidu", position: "MID", rating: 62, rarity: "common", img: "images/cards/la-liga/atletico-de-madrid/taufikseidu.png", teams: ["Atletico de Madrid"], country: "Spain" },
  { id: 91, name: "Luis Aragones", position: "MID", rating: 96, rarity: "relic", img: "images/cards/retired/retired/luisaragones.png", teams: ["retired"], country: "Spain" },
  { id: 92, name: "Kenny Daglish", position: "ATK", rating: 97, rarity: "relic", img: "images/cards/retired/retired/kennydaglish.png", teams: ["retired"], country: "Scotland" },
  { id: 93, name: "Alisson Becker", position: "GK", rating: 89, rarity: "epic", img: "images/cards/premier-league/liverpool/alissonbecker.png", teams: ["Liverpool"], country: "Brasil" },
  { id: 94, name: "Giorgi Mamardashvili", position: "GK", rating: 85, rarity: "rare", img: "images/cards/premier-league/liverpool/giorgimamardashvili.png", teams: ["Liverpool"], country: "Georgia" },
  { id: 95, name: "Freddie Woodman", position: "GK", rating: 71, rarity: "common", img: "images/cards/premier-league/liverpool/freddiewoodman.png", teams: ["Liverpool"], country: "England" },
  { id: 96, name: "Ármin Pécsi", position: "GK", rating: 63, rarity: "common", img: "images/cards/premier-league/liverpool/arminpecsi.png", teams: ["Liverpool"], country: "Hungary" },
  { id: 97, name: "Joe Gomez", position: "DEF", rating: 81, rarity: "common", img: "images/cards/premier-league/liverpool/joegomez.png", teams: ["Liverpool"], country: "England" },
  { id: 98, name: "Virgil Van Dijk", position: "DEF", rating: 89, rarity: "epic", img: "images/cards/premier-league/liverpool/virgilvandijk.png", teams: ["Liverpool"], country: "England" },
  { id: 99, name: "Ibrahima Konate", position: "DEF", rating: 87, rarity: "epic", img: "images/cards/premier-league/liverpool/ibrahimakonate.png", teams: ["Liverpool"], country: "France" },
  { id: 100, name: "Milos Kerkez", position: "DEF", rating: 82, rarity: "common", img: "images/cards/premier-league/liverpool/miloskerkez.png", teams: ["Liverpool"], country: "Hungary" },
  { id: 101, name: "Conor Bradley", position: "DEF", rating: 82, rarity: "common", img: "images/cards/premier-league/liverpool/conorbradley.png", teams: ["Liverpool"], country: "Northern Ireland" },
  { id: 102, name: "Giovanni Leoni", position: "DEF", rating: 67, rarity: "common", img: "images/cards/premier-league/liverpool/giovannileoni.png", teams: ["Liverpool"], country: "Italy" },
  { id: 103, name: "Andy Robertson", position: "DEF", rating: 82, rarity: "common", img: "images/cards/premier-league/liverpool/andyrobertson.png", teams: ["Liverpool"], country: "Scotland" },
  { id: 104, name: "Jeremie Frimpong", position: "DEF", rating: 85, rarity: "rare", img: "images/cards/premier-league/liverpool/jeremiefrimpong.png", teams: ["Liverpool"], country: "Netherlands" },
  { id: 105, name: "Rhys Williams", position: "DEF", rating: 60, rarity: "common", img: "images/cards/premier-league/liverpool/rhyswilliams.png", teams: ["Liverpool"], country: "England" },
  { id: 106, name: "Wataru Endo", position: "MID", rating: 78, rarity: "common", img: "images/cards/premier-league/liverpool/wataruendo.png", teams: ["Liverpool"], country: "Japan" },
  { id: 107, name: "Florian Wirtz", position: "MID", rating: 92, rarity: "legendary", img: "images/cards/premier-league/liverpool/florianwirtz.png", teams: ["Liverpool"], country: "Germany" },
  { id: 108, name: "Dominik Szoboszlai", position: "MID", rating: 86, rarity: "rare", img: "images/cards/premier-league/liverpool/dominikszoboszlai.png", teams: ["Liverpool"], country: "Hungary" },
  { id: 109, name: "Alexis Mac Allister", position: "MID", rating: 88, rarity: "epic", img: "images/cards/premier-league/liverpool/alexismacallister.png", teams: ["Liverpool"], country: "Argentina" },
  { id: 110, name: "Curtis Jones", position: "MID", rating: 80, rarity: "common", img: "images/cards/premier-league/liverpool/curtisjones.png", teams: ["Liverpool"], country: "England" },
  { id: 111, name: "Ryan Gravenberch", position: "MID", rating: 88, rarity: "epic", img: "images/cards/premier-league/liverpool/ryangravenberch.png", teams: ["Liverpool"], country: "Netherlands" },
  { id: 112, name: "Trey Nyoni", position: "MID", rating: 65, rarity: "common", img: "images/cards/premier-league/liverpool/treynyoni.png", teams: ["Liverpool"], country: "England" },
  { id: 113, name: "Stefan Bajcetic", position: "MID", rating: 74, rarity: "common", img: "images/cards/premier-league/liverpool/stefanbajcetic.png", teams: ["Liverpool"], country: "Spain" },
  { id: 114, name: "Kieran Morrison", position: "MID", rating: 61, rarity: "common", img: "images/cards/premier-league/liverpool/kieranmorrison.png", teams: ["Liverpool"], country: "Northern Ireland" },
  { id: 115, name: "Alexander Isak", position: "ATK", rating: 92, rarity: "legendary", img: "images/cards/premier-league/liverpool/alexanderisak.png", teams: ["Liverpool"], country: "Sweden" },
  { id: 116, name: "Mohamed Salah", position: "ATK", rating: 93, rarity: "legendary", img: "images/cards/premier-league/liverpool/mohamedsalah.png", teams: ["Liverpool"], country: "Egypt" },
  { id: 117, name: "Federico Chiesa", position: "ATK", rating: 81, rarity: "common", img: "images/cards/premier-league/liverpool/federicochiesa.png", teams: ["Liverpool"], country: "Italy" },
  { id: 118, name: "Cody Gakpo", position: "ATK", rating: 84, rarity: "rare", img: "images/cards/premier-league/liverpool/codygakpo.png", teams: ["Liverpool"], country: "Netherlands" },
  { id: 119, name: "Hugo Ekitike", position: "ATK", rating: 83, rarity: "rare", img: "images/cards/premier-league/liverpool/hugoekitike.png", teams: ["Liverpool"], country: "France" },
  { id: 120, name: "Kaide Gordon", position: "ATK", rating: 63, rarity: "common", img: "images/cards/premier-league/liverpool/kaidegordon.png", teams: ["Liverpool"], country: "England" },
  { id: 121, name: "Rio Ngumoha", position: "ATK", rating: 63, rarity: "common", img: "images/cards/premier-league/liverpool/riongumoha.png", teams: ["Liverpool"], country: "England" },
  { id: 122, name: "Keyrol Figueroa", position: "ATK", rating: 60, rarity: "common", img: "images/cards/premier-league/liverpool/keyrolfigueroa.png", teams: ["Liverpool"], country: "EEUU" },
];
